//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var infoPlist: infoPlist { .init(source: .init(bundle: bundle, tableName: "InfoPlist", preferredLanguages: preferredLanguages, locale: locale)) }
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func infoPlist(preferredLanguages: [String]) -> infoPlist {
      .init(source: .init(bundle: bundle, tableName: "InfoPlist", preferredLanguages: preferredLanguages, locale: locale))
    }
    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.infoPlist` struct is generated, and contains static references to 2 localization keys.
    struct infoPlist {
      let source: RswiftResources.StringResource.Source

      /// en translation: Stella Pay
      ///
      /// Key: CFBundleDisplayName
      ///
      /// Locales: en, zh-Hans
      var cfBundleDisplayName: RswiftResources.StringResource { .init(key: "CFBundleDisplayName", tableName: "InfoPlist", source: source, developmentValue: "Stella Pay", comment: nil) }

      /// en translation: Need to use your biometric information to lock in your app.
      ///
      /// Key: NSFaceIDUsageDescription
      ///
      /// Locales: en, zh-Hans
      var nsFaceIDUsageDescription: RswiftResources.StringResource { .init(key: "NSFaceIDUsageDescription", tableName: "InfoPlist", source: source, developmentValue: "Need to use your biometric information to lock in your app.", comment: nil) }
    }

    /// This `_R.string.localizable` struct is generated, and contains static references to 2 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: We need to use your Face ID to unlock the screen
      ///
      /// Key: LocalAuthenticationFaceIdLocalizedReason
      ///
      /// Locales: en, zh-Hans
      var localAuthenticationFaceIdLocalizedReason: RswiftResources.StringResource { .init(key: "LocalAuthenticationFaceIdLocalizedReason", tableName: "Localizable", source: source, developmentValue: "We need to use your Face ID to unlock the screen", comment: nil) }

      /// en translation: We need to use your Touch ID to unlock the screen
      ///
      /// Key: LocalAuthenticationTouchIdLocalizedReason
      ///
      /// Locales: en, zh-Hans
      var localAuthenticationTouchIdLocalizedReason: RswiftResources.StringResource { .init(key: "LocalAuthenticationTouchIdLocalizedReason", tableName: "Localizable", source: source, developmentValue: "We need to use your Touch ID to unlock the screen", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 19 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `fw#000000`.
    var fw000000: RswiftResources.ColorResource { .init(name: "fw#000000", path: [], bundle: bundle) }

    /// Color `fw#001214`.
    var fw001214: RswiftResources.ColorResource { .init(name: "fw#001214", path: [], bundle: bundle) }

    /// Color `fw#00191C`.
    var fw00191C: RswiftResources.ColorResource { .init(name: "fw#00191C", path: [], bundle: bundle) }

    /// Color `fw#004396`.
    var fw004396: RswiftResources.ColorResource { .init(name: "fw#004396", path: [], bundle: bundle) }

    /// Color `fw#005960`.
    var fw005960: RswiftResources.ColorResource { .init(name: "fw#005960", path: [], bundle: bundle) }

    /// Color `fw#007481`.
    var fw007481: RswiftResources.ColorResource { .init(name: "fw#007481", path: [], bundle: bundle) }

    /// Color `fw#008999`.
    var fw008999: RswiftResources.ColorResource { .init(name: "fw#008999", path: [], bundle: bundle) }

    /// Color `fw#00A8BB`.
    var fw00A8BB: RswiftResources.ColorResource { .init(name: "fw#00A8BB", path: [], bundle: bundle) }

    /// Color `fw#00A9B5`.
    var fw00A9B5: RswiftResources.ColorResource { .init(name: "fw#00A9B5", path: [], bundle: bundle) }

    /// Color `fw#00C0B3`.
    var fw00C0B3: RswiftResources.ColorResource { .init(name: "fw#00C0B3", path: [], bundle: bundle) }

    /// Color `fw#095CAB`.
    var fw095CAB: RswiftResources.ColorResource { .init(name: "fw#095CAB", path: [], bundle: bundle) }

    /// Color `fw#76A4A7`.
    var fw76A4A7: RswiftResources.ColorResource { .init(name: "fw#76A4A7", path: [], bundle: bundle) }

    /// Color `fw#999999`.
    var fw999999: RswiftResources.ColorResource { .init(name: "fw#999999", path: [], bundle: bundle) }

    /// Color `fw#D3E9F0`.
    var fwD3E9F0: RswiftResources.ColorResource { .init(name: "fw#D3E9F0", path: [], bundle: bundle) }

    /// Color `fw#ED4949`.
    var fwED4949: RswiftResources.ColorResource { .init(name: "fw#ED4949", path: [], bundle: bundle) }

    /// Color `fw#F5F5F7`.
    var fwF5F5F7: RswiftResources.ColorResource { .init(name: "fw#F5F5F7", path: [], bundle: bundle) }

    /// Color `fw#FAFAFA`.
    var fwFAFAFA: RswiftResources.ColorResource { .init(name: "fw#FAFAFA", path: [], bundle: bundle) }

    /// Color `fw#FFFFFF`.
    var fwFFFFFF: RswiftResources.ColorResource { .init(name: "fw#FFFFFF", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 55 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `bg_reg_pic_success`.
    var bg_reg_pic_success: RswiftResources.ImageResource { .init(name: "bg_reg_pic_success", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bg_thanks`.
    var bg_thanks: RswiftResources.ImageResource { .init(name: "bg_thanks", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `guide_bg_intro_1`.
    var guide_bg_intro_1: RswiftResources.ImageResource { .init(name: "guide_bg_intro_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `guide_bg_intro_2`.
    var guide_bg_intro_2: RswiftResources.ImageResource { .init(name: "guide_bg_intro_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `guide_bg_intro_3`.
    var guide_bg_intro_3: RswiftResources.ImageResource { .init(name: "guide_bg_intro_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `guide_bg_intro_4`.
    var guide_bg_intro_4: RswiftResources.ImageResource { .init(name: "guide_bg_intro_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconAddCard`.
    var iconAddCard: RswiftResources.ImageResource { .init(name: "iconAddCard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconAddress`.
    var iconAddress: RswiftResources.ImageResource { .init(name: "iconAddress", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconBack`.
    var iconBack: RswiftResources.ImageResource { .init(name: "iconBack", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconBackInfo`.
    var iconBackInfo: RswiftResources.ImageResource { .init(name: "iconBackInfo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconBtc`.
    var iconBtc: RswiftResources.ImageResource { .init(name: "iconBtc", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconCard`.
    var iconCard: RswiftResources.ImageResource { .init(name: "iconCard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconCardDetail`.
    var iconCardDetail: RswiftResources.ImageResource { .init(name: "iconCardDetail", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconCardSetting`.
    var iconCardSetting: RswiftResources.ImageResource { .init(name: "iconCardSetting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconCloseButton`.
    var iconCloseButton: RswiftResources.ImageResource { .init(name: "iconCloseButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconDeposit`.
    var iconDeposit: RswiftResources.ImageResource { .init(name: "iconDeposit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconDone`.
    var iconDone: RswiftResources.ImageResource { .init(name: "iconDone", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconDownArrow`.
    var iconDownArrow: RswiftResources.ImageResource { .init(name: "iconDownArrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconExactitude`.
    var iconExactitude: RswiftResources.ImageResource { .init(name: "iconExactitude", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconExactitudeButton`.
    var iconExactitudeButton: RswiftResources.ImageResource { .init(name: "iconExactitudeButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconFilterButton`.
    var iconFilterButton: RswiftResources.ImageResource { .init(name: "iconFilterButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconFrom`.
    var iconFrom: RswiftResources.ImageResource { .init(name: "iconFrom", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconInfo`.
    var iconInfo: RswiftResources.ImageResource { .init(name: "iconInfo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconLTC`.
    var iconLTC: RswiftResources.ImageResource { .init(name: "iconLTC", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconLogo`.
    var iconLogo: RswiftResources.ImageResource { .init(name: "iconLogo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconMore`.
    var iconMore: RswiftResources.ImageResource { .init(name: "iconMore", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconPassport`.
    var iconPassport: RswiftResources.ImageResource { .init(name: "iconPassport", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconPasswordHide`.
    var iconPasswordHide: RswiftResources.ImageResource { .init(name: "iconPasswordHide", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconPasswordShow`.
    var iconPasswordShow: RswiftResources.ImageResource { .init(name: "iconPasswordShow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconProfile`.
    var iconProfile: RswiftResources.ImageResource { .init(name: "iconProfile", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconRefreshButton`.
    var iconRefreshButton: RswiftResources.ImageResource { .init(name: "iconRefreshButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconRegisterCheckboxOff`.
    var iconRegisterCheckboxOff: RswiftResources.ImageResource { .init(name: "iconRegisterCheckboxOff", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconRegisterCheckboxOn`.
    var iconRegisterCheckboxOn: RswiftResources.ImageResource { .init(name: "iconRegisterCheckboxOn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconRightArrowBlue`.
    var iconRightArrowBlue: RswiftResources.ImageResource { .init(name: "iconRightArrowBlue", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconRightArrowGray`.
    var iconRightArrowGray: RswiftResources.ImageResource { .init(name: "iconRightArrowGray", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconRightArrowGreen`.
    var iconRightArrowGreen: RswiftResources.ImageResource { .init(name: "iconRightArrowGreen", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconRightArrowWhite`.
    var iconRightArrowWhite: RswiftResources.ImageResource { .init(name: "iconRightArrowWhite", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconSelfie`.
    var iconSelfie: RswiftResources.ImageResource { .init(name: "iconSelfie", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconSell`.
    var iconSell: RswiftResources.ImageResource { .init(name: "iconSell", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconShareButton`.
    var iconShareButton: RswiftResources.ImageResource { .init(name: "iconShareButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconStatement`.
    var iconStatement: RswiftResources.ImageResource { .init(name: "iconStatement", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTabbarCard`.
    var iconTabbarCard: RswiftResources.ImageResource { .init(name: "iconTabbarCard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTabbarCardSelected`.
    var iconTabbarCardSelected: RswiftResources.ImageResource { .init(name: "iconTabbarCardSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTabbarHome`.
    var iconTabbarHome: RswiftResources.ImageResource { .init(name: "iconTabbarHome", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTabbarHomeSelected`.
    var iconTabbarHomeSelected: RswiftResources.ImageResource { .init(name: "iconTabbarHomeSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTabbarWallet`.
    var iconTabbarWallet: RswiftResources.ImageResource { .init(name: "iconTabbarWallet", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTabbarWalletSelected`.
    var iconTabbarWalletSelected: RswiftResources.ImageResource { .init(name: "iconTabbarWalletSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTick`.
    var iconTick: RswiftResources.ImageResource { .init(name: "iconTick", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTickOff`.
    var iconTickOff: RswiftResources.ImageResource { .init(name: "iconTickOff", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconTickOn`.
    var iconTickOn: RswiftResources.ImageResource { .init(name: "iconTickOn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconUser`.
    var iconUser: RswiftResources.ImageResource { .init(name: "iconUser", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `iconWithdraw`.
    var iconWithdraw: RswiftResources.ImageResource { .init(name: "iconWithdraw", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_faceid`.
    var icon_faceid: RswiftResources.ImageResource { .init(name: "icon_faceid", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lanuchscreen_bg`.
    var lanuchscreen_bg: RswiftResources.ImageResource { .init(name: "lanuchscreen_bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lanuchscreen_logo`.
    var lanuchscreen_logo: RswiftResources.ImageResource { .init(name: "lanuchscreen_logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.font` struct is generated, and contains static references to 6 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `DIN-Bold`.
    var dinBold: RswiftResources.FontResource { .init(name: "DIN-Bold", bundle: bundle, filename: "din-bold.ttf") }

    /// Font `DIN-Regular`.
    var dinRegular: RswiftResources.FontResource { .init(name: "DIN-Regular", bundle: bundle, filename: "din-regular.ttf") }

    /// Font `Roboto-Bold`.
    var robotoBold: RswiftResources.FontResource { .init(name: "Roboto-Bold", bundle: bundle, filename: "Roboto-Bold-3.ttf") }

    /// Font `Roboto-Light`.
    var robotoLight: RswiftResources.FontResource { .init(name: "Roboto-Light", bundle: bundle, filename: "Roboto-Light-10.ttf") }

    /// Font `Roboto-Medium`.
    var robotoMedium: RswiftResources.FontResource { .init(name: "Roboto-Medium", bundle: bundle, filename: "Roboto-Medium-12.ttf") }

    /// Font `Roboto-Regular`.
    var robotoRegular: RswiftResources.FontResource { .init(name: "Roboto-Regular", bundle: bundle, filename: "Roboto-Regular-14.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [dinBold, dinRegular, robotoBold, robotoLight, robotoMedium, robotoRegular].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 6 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Roboto-Bold-3.ttf`.
    var robotoBold3Ttf: RswiftResources.FileResource { .init(name: "Roboto-Bold-3", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Roboto-Light-10.ttf`.
    var robotoLight10Ttf: RswiftResources.FileResource { .init(name: "Roboto-Light-10", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Roboto-Medium-12.ttf`.
    var robotoMedium12Ttf: RswiftResources.FileResource { .init(name: "Roboto-Medium-12", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Roboto-Regular-14.ttf`.
    var robotoRegular14Ttf: RswiftResources.FileResource { .init(name: "Roboto-Regular-14", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `din-bold.ttf`.
    var dinBoldTtf: RswiftResources.FileResource { .init(name: "din-bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `din-regular.ttf`.
    var dinRegularTtf: RswiftResources.FileResource { .init(name: "din-regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 49 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `ApplyCardSuccessViewController`.
    var applyCardSuccessViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ApplyCardSuccessViewController", bundle: bundle) }

    /// Nib `ApplyCardViewController`.
    var applyCardViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ApplyCardViewController", bundle: bundle) }

    /// Nib `BindPhoneViewController`.
    var bindPhoneViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "BindPhoneViewController", bundle: bundle) }

    /// Nib `BiometricsViewController`.
    var biometricsViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "BiometricsViewController", bundle: bundle) }

    /// Nib `CardBagTableViewCell`.
    var cardBagTableViewCell: RswiftResources.NibReference<CardBagTableViewCell> { .init(name: "CardBagTableViewCell", bundle: bundle) }

    /// Nib `CardDetailViewController`.
    var cardDetailViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CardDetailViewController", bundle: bundle) }

    /// Nib `CardSettingTableViewCell`.
    var cardSettingTableViewCell: RswiftResources.NibReference<CardSettingTableViewCell> { .init(name: "CardSettingTableViewCell", bundle: bundle) }

    /// Nib `CardSettingViewController`.
    var cardSettingViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CardSettingViewController", bundle: bundle) }

    /// Nib `CardTableViewCell`.
    var cardTableViewCell: RswiftResources.NibReference<CardTableViewCell> { .init(name: "CardTableViewCell", bundle: bundle) }

    /// Nib `CardViewController`.
    var cardViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CardViewController", bundle: bundle) }

    /// Nib `ChooseDateView`.
    var chooseDateView: RswiftResources.NibReference<ChooseDateView> { .init(name: "ChooseDateView", bundle: bundle) }

    /// Nib `ChooseRegionTableViewCell`.
    var chooseRegionTableViewCell: RswiftResources.NibReference<ChooseRegionTableViewCell> { .init(name: "ChooseRegionTableViewCell", bundle: bundle) }

    /// Nib `ChooseRegionViewController`.
    var chooseRegionViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ChooseRegionViewController", bundle: bundle) }

    /// Nib `CryptoWalletDetailViewController`.
    var cryptoWalletDetailViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CryptoWalletDetailViewController", bundle: bundle) }

    /// Nib `DepositFromTableViewCell`.
    var depositFromTableViewCell: RswiftResources.NibReference<DepositFromTableViewCell> { .init(name: "DepositFromTableViewCell", bundle: bundle) }

    /// Nib `DepositFromView`.
    var depositFromView: RswiftResources.NibReference<DepositFromView> { .init(name: "DepositFromView", bundle: bundle) }

    /// Nib `EmptyCardTableViewCell`.
    var emptyCardTableViewCell: RswiftResources.NibReference<EmptyCardTableViewCell> { .init(name: "EmptyCardTableViewCell", bundle: bundle) }

    /// Nib `FillInAddressViewController`.
    var fillInAddressViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "FillInAddressViewController", bundle: bundle) }

    /// Nib `FillInNameAndNationalViewController`.
    var fillInNameAndNationalViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "FillInNameAndNationalViewController", bundle: bundle) }

    /// Nib `ForgotPasswordEmailCheckViewController`.
    var forgotPasswordEmailCheckViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ForgotPasswordEmailCheckViewController", bundle: bundle) }

    /// Nib `FreezeSuccessViewController`.
    var freezeSuccessViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "FreezeSuccessViewController", bundle: bundle) }

    /// Nib `GuidePagerViewCell`.
    var guidePagerViewCell: RswiftResources.NibReference<GuidePagerViewCell> { .init(name: "GuidePagerViewCell", bundle: bundle) }

    /// Nib `GuideViewController`.
    var guideViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "GuideViewController", bundle: bundle) }

    /// Nib `HomeViewController`.
    var homeViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "HomeViewController", bundle: bundle) }

    /// Nib `KYCFillInNameAndNationalViewController`.
    var kycFillInNameAndNationalViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "KYCFillInNameAndNationalViewController", bundle: bundle) }

    /// Nib `KYCFinishViewController`.
    var kycFinishViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "KYCFinishViewController", bundle: bundle) }

    /// Nib `KYCUnAvailableViewController`.
    var kycUnAvailableViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "KYCUnAvailableViewController", bundle: bundle) }

    /// Nib `LockScreenViewController`.
    var lockScreenViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LockScreenViewController", bundle: bundle) }

    /// Nib `LoginViewController`.
    var loginViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LoginViewController", bundle: bundle) }

    /// Nib `PasswordLoginViewController`.
    var passwordLoginViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PasswordLoginViewController", bundle: bundle) }

    /// Nib `RecentTransactionsTableViewCell`.
    var recentTransactionsTableViewCell: RswiftResources.NibReference<RecentTransactionsTableViewCell> { .init(name: "RecentTransactionsTableViewCell", bundle: bundle) }

    /// Nib `RegisterViewController`.
    var registerViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "RegisterViewController", bundle: bundle) }

    /// Nib `SecurityVerificationViewController`.
    var securityVerificationViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SecurityVerificationViewController", bundle: bundle) }

    /// Nib `SettingNewPasswordViewController`.
    var settingNewPasswordViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SettingNewPasswordViewController", bundle: bundle) }

    /// Nib `SettingPasswordTipsTableViewCell`.
    var settingPasswordTipsTableViewCell: RswiftResources.NibReference<SettingPasswordTipsTableViewCell> { .init(name: "SettingPasswordTipsTableViewCell", bundle: bundle) }

    /// Nib `SettingPasswordViewController`.
    var settingPasswordViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SettingPasswordViewController", bundle: bundle) }

    /// Nib `StartExperienceViewController`.
    var startExperienceViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "StartExperienceViewController", bundle: bundle) }

    /// Nib `TransactionItemTableViewCell`.
    var transactionItemTableViewCell: RswiftResources.NibReference<TransactionItemTableViewCell> { .init(name: "TransactionItemTableViewCell", bundle: bundle) }

    /// Nib `TransactionTableViewCell`.
    var transactionTableViewCell: RswiftResources.NibReference<TransactionTableViewCell> { .init(name: "TransactionTableViewCell", bundle: bundle) }

    /// Nib `TransactionsFilterCollectionViewCell`.
    var transactionsFilterCollectionViewCell: RswiftResources.NibReference<TransactionsFilterCollectionViewCell> { .init(name: "TransactionsFilterCollectionViewCell", bundle: bundle) }

    /// Nib `TransactionsFilterDateCollectionViewCell`.
    var transactionsFilterDateCollectionViewCell: RswiftResources.NibReference<TransactionsFilterDateCollectionViewCell> { .init(name: "TransactionsFilterDateCollectionViewCell", bundle: bundle) }

    /// Nib `TransactionsFilterViewController`.
    var transactionsFilterViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "TransactionsFilterViewController", bundle: bundle) }

    /// Nib `TransactionsViewController`.
    var transactionsViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "TransactionsViewController", bundle: bundle) }

    /// Nib `VerificationCodeViewController`.
    var verificationCodeViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "VerificationCodeViewController", bundle: bundle) }

    /// Nib `VerifyYourIdentityGuideViewController`.
    var verifyYourIdentityGuideViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "VerifyYourIdentityGuideViewController", bundle: bundle) }

    /// Nib `WalletCardTableViewCell`.
    var walletCardTableViewCell: RswiftResources.NibReference<WalletCardTableViewCell> { .init(name: "WalletCardTableViewCell", bundle: bundle) }

    /// Nib `WalletCryptoItemTableViewCell`.
    var walletCryptoItemTableViewCell: RswiftResources.NibReference<WalletCryptoItemTableViewCell> { .init(name: "WalletCryptoItemTableViewCell", bundle: bundle) }

    /// Nib `WalletCryptoTableViewCell`.
    var walletCryptoTableViewCell: RswiftResources.NibReference<WalletCryptoTableViewCell> { .init(name: "WalletCryptoTableViewCell", bundle: bundle) }

    /// Nib `WalletViewController`.
    var walletViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "WalletViewController", bundle: bundle) }

    func validate() throws {
      if UIKit.UIImage(named: "iconCard", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconCard' is used in nib 'ApplyCardSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconTick", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconTick' is used in nib 'ApplyCardSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'ApplyCardSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'ApplyCardSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'ApplyCardSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconExactitude", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconExactitude' is used in nib 'ApplyCardViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconInfo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconInfo' is used in nib 'ApplyCardViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'ApplyCardViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'ApplyCardViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'ApplyCardViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconDownArrow", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconDownArrow' is used in nib 'BindPhoneViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconInfo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconInfo' is used in nib 'BindPhoneViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'BindPhoneViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'BindPhoneViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'BindPhoneViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "icon_faceid", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'icon_faceid' is used in nib 'BiometricsViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconBackInfo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconBackInfo' is used in nib 'CardBagTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconCardDetail", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconCardDetail' is used in nib 'CardBagTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconDeposit", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconDeposit' is used in nib 'CardBagTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconStatement", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconStatement' is used in nib 'CardBagTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'CardBagTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'CardBagTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconRightArrowBlue", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconRightArrowBlue' is used in nib 'CardSettingTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'CardSettingTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'CardSettingTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FAFAFA", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FAFAFA' is used in nib 'CardSettingTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'CardSettingViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FAFAFA", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FAFAFA' is used in nib 'CardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'CardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconCardSetting", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconCardSetting' is used in nib 'CardViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'ChooseDateView', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#76A4A7", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#76A4A7' is used in nib 'ChooseDateView', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'ChooseDateView', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'ChooseRegionTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'ChooseRegionViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'ChooseRegionViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconDeposit", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconDeposit' is used in nib 'CryptoWalletDetailViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconSell", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconSell' is used in nib 'CryptoWalletDetailViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconWithdraw", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconWithdraw' is used in nib 'CryptoWalletDetailViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'CryptoWalletDetailViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'CryptoWalletDetailViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconBtc", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconBtc' is used in nib 'DepositFromTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconRightArrowGreen", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconRightArrowGreen' is used in nib 'DepositFromTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'DepositFromTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#76A4A7", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#76A4A7' is used in nib 'DepositFromTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'DepositFromView', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#76A4A7", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#76A4A7' is used in nib 'DepositFromView', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'DepositFromView', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconAddCard", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconAddCard' is used in nib 'EmptyCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'EmptyCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FAFAFA", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FAFAFA' is used in nib 'EmptyCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'EmptyCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'FillInAddressViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'FillInAddressViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconInfo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconInfo' is used in nib 'FillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'FillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'FillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'FillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'ForgotPasswordEmailCheckViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'ForgotPasswordEmailCheckViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'ForgotPasswordEmailCheckViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconDone", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconDone' is used in nib 'FreezeSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'FreezeSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'FreezeSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'FreezeSuccessViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "guide_bg_intro_3", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'guide_bg_intro_3' is used in nib 'GuidePagerViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'GuidePagerViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "colorFFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'colorFFFFFF' is used in nib 'GuideViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A9B5", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A9B5' is used in nib 'GuideViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconInfo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconInfo' is used in nib 'KYCFillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'KYCFillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00191C", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00191C' is used in nib 'KYCFillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'KYCFillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#ED4949", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#ED4949' is used in nib 'KYCFillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'KYCFillInNameAndNationalViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconProfile", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconProfile' is used in nib 'KYCFinishViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconTick", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconTick' is used in nib 'KYCFinishViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'KYCFinishViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'KYCFinishViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'KYCFinishViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconProfile", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconProfile' is used in nib 'KYCUnAvailableViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'KYCUnAvailableViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'KYCUnAvailableViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'KYCUnAvailableViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'LoginViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'LoginViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconLogo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconLogo' is used in nib 'PasswordLoginViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'PasswordLoginViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'PasswordLoginViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'RecentTransactionsTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconRegisterCheckboxOff", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconRegisterCheckboxOff' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconRegisterCheckboxOn", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconRegisterCheckboxOn' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#ED4949", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#ED4949' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'RegisterViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconInfo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconInfo' is used in nib 'SecurityVerificationViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'SecurityVerificationViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'SecurityVerificationViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'SecurityVerificationViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'SettingNewPasswordViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'SettingNewPasswordViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'SettingNewPasswordViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconTickOff", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconTickOff' is used in nib 'SettingPasswordTipsTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'SettingPasswordTipsTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'SettingPasswordViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'SettingPasswordViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "bg_reg_pic_success", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bg_reg_pic_success' is used in nib 'StartExperienceViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "bg_thanks", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bg_thanks' is used in nib 'StartExperienceViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'StartExperienceViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'StartExperienceViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "#999999", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named '#999999' is used in nib 'TransactionItemTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'TransactionTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A9B5", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A9B5' is used in nib 'TransactionTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#999999", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#999999' is used in nib 'TransactionTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'TransactionsFilterCollectionViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconRightArrowWhite", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconRightArrowWhite' is used in nib 'TransactionsFilterDateCollectionViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#F5F5F7", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#F5F5F7' is used in nib 'TransactionsFilterDateCollectionViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'TransactionsFilterDateCollectionViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'TransactionsViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#F5F5F7", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#F5F5F7' is used in nib 'TransactionsViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'TransactionsViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'VerificationCodeViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'VerificationCodeViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#ED4949", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#ED4949' is used in nib 'VerificationCodeViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'VerificationCodeViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconAddress", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconAddress' is used in nib 'VerifyYourIdentityGuideViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconPassport", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconPassport' is used in nib 'VerifyYourIdentityGuideViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconProfile", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconProfile' is used in nib 'VerifyYourIdentityGuideViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconSelfie", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconSelfie' is used in nib 'VerifyYourIdentityGuideViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconUser", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconUser' is used in nib 'VerifyYourIdentityGuideViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'VerifyYourIdentityGuideViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'VerifyYourIdentityGuideViewController', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'VerifyYourIdentityGuideViewController', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconDeposit", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconDeposit' is used in nib 'WalletCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconSell", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconSell' is used in nib 'WalletCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconWithdraw", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconWithdraw' is used in nib 'WalletCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'WalletCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#00A8BB", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#00A8BB' is used in nib 'WalletCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FAFAFA", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FAFAFA' is used in nib 'WalletCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#FFFFFF", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#FFFFFF' is used in nib 'WalletCardTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconBtc", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconBtc' is used in nib 'WalletCryptoItemTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "iconRightArrowBlue", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'iconRightArrowBlue' is used in nib 'WalletCryptoItemTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "fw#000000", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'fw#000000' is used in nib 'WalletCryptoTableViewCell', but couldn't be loaded.") }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {
        if UIKit.UIImage(named: "lanuchscreen_bg", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'lanuchscreen_bg' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if UIKit.UIImage(named: "lanuchscreen_logo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'lanuchscreen_logo' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
    }
  }
}